* Jan
** Nieuwolda

Recent engels oud voor de eerste, maar Jan was er tweede.

** Klompen
** Biljarten

Ballen, trekken en doorstoten op donderdagavond.

** Dammen

Dubbele stenen om water te keren.

** Bartelomeus
** Geschiedenis

Was vroeger minder.

** Belastinginspecteur

Functie om nederlandse inkomsten te checken.

** Klaverjassen

Kan geluk brengen voor buitenkleding voor vier spelende broers. 

** Groninger

Bovenstebeste nederlander

** Piepers jassen
** Femmie/Femmigje

Medeplichtige in wilde nacht met hospita als getuige.

** Strohoed

Schaduw van gedroogd koren.

** Kennis

Bekende. Niets totdat het wordt begrepen.

** Schaatsen

IJsers?

** Diabetes

Hierdoor worden er voor hem geen zoete broodjes meer gebakken.

** Herseninfarct/beroerte

 Gevaarlijke stop tussen je oren.

** Borrel

Klein maar sterk.

** Pacifist

Daar maak je geen soldaat van.

** Boxer
** Wollensokken
** Bretels

Deze hangers geven je met stijl een kans tegen de zwaartekracht.

** Taal/taalkenner

Begrijpelijk per definitie, maar ook vaak niet.

** Zonderling
** Einzelgänger

Eenzame buur.

** Vader
** Puzzelen

Tijdverknoeien of tijdverdrijven?

** Streng
** Broer

Kan ze niet zijn maar hebben.

** Soldaat
** Opa

Doet Ivor en Elvi praten over het onbeklede achterwerk.

** Secretaris
** SOS

Afgekort zijn favoriete verjaardagskadootjes.

** Konijneboer
** Natuurliefhebber
** Hoofdrekenaar

Menselijke computer.

** Mol

Bijnaam voor stoffige gangenmaker.

** Bril

Geeft buitenlichamelijk betere gewaarwording van ver en dichtbij.

** Zwijgzaam

Niet sprekend, maar wel voor hem.

** Belastingdienst

Maakt teruggeven loonzaam voor werknemers.

** Linguist/taalkenner
** Baard

Goed getrimd geeft hij niet aleen de drager minder kriebels.

** Tachtig

Zijn Femmie en Jan.

* Femmie
** Echten

Geen nep tevens een klein, mooi dorp in de provincie.

** Amsterdam

Is verkort als de eerste man waar zij verliefd was.

** Drente

Doctor verkort ook op haar nederlands deelgebied. 

** Bellingwolde

Hier zijn we nu voor haar.

** Jan

Man met een korte achternaam.

** Boxer

Van deze trouwe vechtersbaas was zij de baas.

** Welfare

Bron voor juist engels bezigzijn.

** Fietsen

Trappen op voertuigen.

** Kunstheupen

Truukjes om babies mee in slaap te schommelen?

** Liefdevol

Maximaal genegenheid is zij voor anderen.

** Kloot

Ronde benaming voor haar klungelige medeweggebruiker.

** Brooddag

Groet na meelprodukt waar wat in zit om wekelijks honger te bestrijden.

** Pannekoekjes

Pech bij de koffie dat vroeger vooral woensdag na school gegeten werd.

** Kazerne

Plakken of blokjes met 'r in haar huidig-e huis.

** Oma

Weer de eerste.

** Breien

Hoe ze haar kinderen prikkelt en warmhoudt.

** Schoonmaken
** Gymnastiek
** Nachtzuster

Familielid die haar broer niet bij daglicht ziet.

** Kerk

Als vogelroepen voor en na daar waar het verhaal professioneel verteld wordt.

** Lezen

Doe je nu frans voor de meditatie?

** Mama
** Moeder

Zij is uitgeput van haar kinderen.

** Witlof

Met ham en kaas haalt ze kleurloze roem lekker uit de oven.

** Bloemkool

Geurig en fleurig gewas voor verbrand hout wordt haar lievelingseten.

** Rode wijn
** Gezelligheid

Typisch nederlands en aangenaam doel op zich.

** Kaas
** Nootjes

Om te knabbelen en te zingen.

** Handwerken

Doet ze graag zonder voeten.

** Oud

Dat mag je van 80 wel zeggen, maar ook van de 31e.

** Lief
** Naaien
** Nieuwstatenzijl

Recente toestanden om water te keren en vis te eten.

** Wandelen

En dwalen gaat niet meer zo snel.

** Borduren
** Jonker
** De-Slimste-Mens

Waar knappe personen strijden voor allen te zien.

* Greetje
** Duran Duran
** Zwitserland, Kandersteg
** Bonte koe
** Punk
** Hotelschool
** Paars haar
** Jongste
** Katten, Meneer de Wit
** Reizen
** Groningse
** Gezellig
** schilderen
** Blond(je)
** avontuurlijk
** sociaal
** waterman
** Stephen King
